### ISSUE TITLE
Getting the message "forbidden " when syncing highlights

### ISSUE THREAD

**Issue by sawhney17** [readwiseio/logseq-readwise-official-plugin#1]
<img width="1440" alt="Screenshot 2022-07-05 at 5 58 45 PM" src="https://user-images.githubusercontent.com/80150109/177345184-701de60a-9d73-44b8-ae18-41eda29ca15c.png">

1. Installed the plugin
2. Logged in
3. Switched database
4. Reset the extension
5. Logged in again
6. Click sync
7. Received message

**Comment by sawhney17** [comment]
Awesome!

**Comment by brunojm** [comment]
You have the trial expired, that's why you got this error.
