### ISSUE TITLE
Tweets with bullet points are cut short

### ISSUE THREAD

**Issue by pamil** [readwiseio/logseq-readwise-official-plugin#2]
Eg. this one: https://twitter.com/Mappletons/status/1265608212528717825

On Readwise:
<img width="675" alt="CleanShot 2022-07-06 at 00 48 08@2x" src="https://user-images.githubusercontent.com/1897953/177429576-1f5b6c33-bee0-4348-a58f-abb073ded92d.png">

Synced with LogSeq:
<img width="561" alt="CleanShot 2022-07-06 at 00 48 52@2x" src="https://user-images.githubusercontent.com/1897953/177429611-bc487143-bee1-443d-bc96-a18e42764df5.png">

**Comment by brunojm** [comment]
Thanks for reporting @pamil, I'm on it.

**Comment by pstuifzand** [comment]
I found out that for the Logseq parser blocks can't start with a dash and also lines can't start with a dash. A solution would be to escape `-` with `\\`. Another solution could be to replace `-` with `*`, but that changes the message.

https://github.com/logseq/logseq/issues/5664

**Comment by brunojm** [comment]
Fixed on https://github.com/readwiseio/logseq-readwise-official-plugin/commit/ad313b4255dad6c3478fb0938473111f00f4d52f

**Comment by pstuifzand** [comment]
@brunojm This fix creates a problem with `-` dashes on the line itself. Example is a property `full-title:: Title`, which is imported as: `full\-title:: Title`. Logseq shows an error for this property.
