### ISSUE TITLE
Error after first sync

### ISSUE THREAD

**Issue by Hileotech** [readwiseio/logseq-readwise-official-plugin#3]
As per title, I installed yesterday your plugin (Logseq 0.7.6 running on macOS Monterey 12.4) and after first sync I got the error attached.
Today, as I'm trying to organize my imported highlights, everything worked fine until, a few minutes ago I received the very same error.
![CleanShot 2022-07-06 at 08 57 25@2x](https://user-images.githubusercontent.com/81426495/177489290-0a018f92-fb18-454c-9496-519916d2e9ca.png)

**Comment by brunojm** [comment]
Hello @Hileotech, can you send me your e-mail address registered on Readwise (please send it to bruno@readwise.io)?

**Comment by Hileotech** [comment]
You'll hate in in your email in a few minutes. Thanks!

**Comment by brunojm** [comment]
@Hileotech I tried to reproduce the problem but I wasn't able to reproduce this error... but I found this: https://github.com/logseq/logseq/issues/5613 it seems related with some Logseq bug.
