### ISSUE TITLE
New highlights are not synced

### ISSUE THREAD

**Issue by cschinner** [readwiseio/logseq-readwise-official-plugin#5]
When I add new highlights they are not synced to Readwise. I did not rename any pages so this is not the issue. Currently, the only way for me to get new highlights is to delete the page and initiate a new sync. Any reasons that come to your mind why this happens?

**Comment by brunojm** [comment]
Hello @cschinner can you tell me if this is happening with every kind of content (books, tweets, etc)? Also, are you getting any error on Logseq?

**Comment by cschinner** [comment]
I just tried it with an article and new highlights were synced. However, for books it does not sync the new highlights. I do not get an error in Logseq.

**Comment by xiang0805** [comment]
I find it will delay the sync of time.
for example ,i export the note at 7/15 11:00pm , but it will show at 7/16 journal page

**Comment by xiang0805** [comment]
Do I adjust that at Customize formatting options?

**Comment by xiang0805** [comment]
Do I adjust that at Customize formatting options?

**Comment by brunojm** [comment]
@xiang0805 I found the issue related to the date, should be fixed now.

**Comment by brunojm** [comment]
Thanks @cschinner, any help you need, please open a new issue or send an email to [hello@readwise.io](mailto:hello@readwise.io)
